---
# fastapi role tasks scaffold
# TODO: implement actual provisioning steps (install python, venv, pull repo, systemd service)

- name: Ensure required packages are installed
  apt:
    name:
      - python3.11
      - python3.11-venv
      - git
    state: present
    update_cache: yes

- name: Placeholder for cloning repository
  debug:
    msg: "TODO: git clone repo to target directory"

- name: Placeholder for creating systemd service
  debug:
    msg: "TODO: create and enable systemd service for uvicorn"
